site_name: 生活沉思录
site_description: 博览万物，融会贯通。
site_url: https://docs.fxcdev.com

theme:
  name: material
  font: #false #如果遇到国内网络问题，可选用 false，不启用特殊字体
    text: "Noto Sans SC" # , Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)" # 检查用户系统配置是否为亮色
      scheme: default # 亮色模式
      primary: white # 基本颜色
      accent: blue # 按钮等互动块的颜色
      toggle:
        icon: material/eye
        name: 切换暗色模式
    - media: "(prefers-color-scheme: dark)" # 检查用户系统配置是否为暗色
      scheme: slate # 暗色模式
      primary: black # 基本颜色
      accent: blue # 按钮等互动块的颜色
      toggle:
        icon: material/eye-outline
        name: 切换亮色模式
  language: zh
  logo: assets/img/logo-zip.png #https://cos.ap-guangzhou.myqcloud.com/wiki-media-1253965369/doc/logo-zip.png
  favicon: assets/img/logo.svg #https://cos.ap-guangzhou.myqcloud.com/wiki-media-1253965369/doc/logo.svg #https://cos.ap-guangzhou.myqcloud.com/wiki-media-1253965369/doc/logo-zip.png
  features:
    - content.code.copy # 代码块复制按钮
    - content.action.edit # 文章编辑按钮
    #- navigation.instant # Instant loading，像个单页应用
    - navigation.tracking # Anchor tracking
    - navigation.tabs # 导航栏
    - navigation.footer # 上一篇 / 下一篇导航按钮
    #- navigation.tabs.sticky # 导航栏不随页面滚动隐藏
    - navigation.sections # 侧边栏分组显示
    #- navigation.expand # 导航栏自动展开
    - navigation.indexes # 组标题有专属页面
    - toc.follow # 目录自动跟随
    - navigation.top # 返回顶部按钮
    - search.suggest # 搜索推荐
    #- navigation.prune # 导航修剪，仅渲染可见链接，优化文档数量超过100的站点（实验），会导致页面间跳转速度变慢
    #- search.highlight
  icon:
    repo: material/github
    #edit: material/pencil

plugins:
  - search:
      jieba_dict: dict.txt
  - rss:
      abstract_chars_count: -1 # -1 for full content
      #categories:
      # - tags
      #comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d %H:%M"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 1000
      pretty_print: true
      match_path: ".*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"

copyright: Copyright &copy; 2015 - 2023 by Power | <a href="https://beian.miit.gov.cn"> 陕 ICP 备 19014586 号 </a>

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - mdx_truly_sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdn.jsdelivr.net/npm/pangu@4.0.7/dist/browser/pangu.min.js
  - assets/javascripts/mathjax.js #https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/latest.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js #javascripts/tex-mml-chtml.js
  - assets/javascripts/embed.js # https://viewer.altium.com/client/static/js/embed.js

extra_css:
  - assets/stylesheets/extra.css

nav:
  - 硬件 & 半导体:
      - 硬件设计:
          - 基础知识:
              - 硬件设计/基础知识/基本元器件-电阻.md
  - 嵌入式 & 软件开发:
      - 嵌入式开发:
          - 51 单片机:
              - 嵌入式开发/51 单片机/单片机简介.md
